name: "covost2-de-asr"
joeynmt_version: 1.4

data:
    task: "s2t"
    root_path: "/scratch5t/ohta/covost/de/"
    train: "joey_asr_train"
    dev: "joey_asr_dev"
    test: "joey_asr_test"
    dev_random_subset: 2000 # in order to speed up the validation in the training loop
    src:
        num_freq: 80
        max_length: 3000
    trg:
        lang: "de"
        level: "bpe"
        tokenizer: "sentencepiece" # called "bpe_type" in version<=1.3
        lowercase: False
        remove_punctuation: False
        max_length: 100 # called "max_sent_length" in version<=1.3
        voc_min_freq: 1
        voc_limit: 8000
        voc_file: "/scratch5t/ohta/covost/de/spm_unigram8000.tsv" # called "trg_vocab" in version<=1.3
        spm:
            model_file: "/scratch5t/ohta/covost/de/spm_unigram8000.model"  # sentence piece model path
            enable_sampling: False         # whether to enable BPE dropout
    specaugment:
        freq_mask_n: 1
        freq_mask_f: 18
        time_mask_n: 1
        time_mask_t: 40
        time_mask_p: 1.0
    cmvn:
        norm_means: True
        norm_vars: True
        before: True

testing:
    beam_size: 5
    alpha: 1.0
    sacrebleu:
        remove_punctuation: False
        tokenize: "13a"

training:
    #load_model: "/scratch12t/ohta/models/covost2_de_asr_seed789/latest.ckpt"
    reset_best_ckpt: False
    reset_scheduler: False
    reset_optimizer: False
    reset_iter_state: False
    random_seed: 789
    optimizer: "adam"
    adam_betas: [0.9, 0.99]
    scheduling: "warmupinversesquareroot"
    learning_rate: 2.0e-3
    learning_rate_min: 1.0e-7
    learning_rate_warmup: 10000
    clip_grad_norm: 10.0
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_multiplier: 2
    normalization: "batch"
    batch_size: 80000
    batch_type: "token"
    eval_batch_size: 80000
    eval_batch_type: "token"
    early_stopping_metric: "ppl"
    epochs: 50
    updates: 320000
    validation_freq: 5000
    logging_freq: 500
    eval_metrics: "wer"
    model_dir: "/scratch12t/ohta/models/covost2_de_asr_seed789"
    overwrite: True
    shuffle: True
    use_cuda: True
    fp16: False
    max_output_length: 120
    print_valid_sents: [0, 1, 2]
    keep_best_ckpts: 10
    loss: "crossentropy-ctc"
    ctc_weight: 0.3

model:
    initializer: "xavier"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 12
        num_heads: 8
        embeddings:
            embedding_dim: 80
            #embedding_dim: 512
            #scale: True
            #dropout: 0.
            #freeze: False
        # typically ff_size = 8 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.15
        freeze: False
        subsample: True
        conv_kernel_sizes: 3,3
        conv_channels: 512
        in_channels: 80
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
            freeze: False
        # ff_size = 8 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.15
        freeze: False
