name: "transformer-mustc-asr"

data:
    task: "s2t"
    root_path: "/scratch5t/ohta/MUSTC_v2.0/en-de/"
    train: "train_asr_spm20000"
    dev: "dev_asr_spm20000"
    test: "tst-COMMON_asr_spm20000"
    level: "bpe"
    lowercase: True
    max_sent_length: 80
    max_feat_length: 3000
    num_freq: 80
    #src_voc_min_freq: 1
    #src_voc_limit: 20000
    trg_voc_min_freq: 1
    trg_voc_limit: 20000
    #src_vocab: "/scratch5t/ohta/MUSTC_v2.0/en-de/spm_unigram20000.txt"
    trg_vocab: "/scratch5t/ohta/MUSTC_v2.0/en-de/spm_unigram20000.txt"
    specaugment:
        freq_mask_n: 2
        freq_mask_f: 27
        time_mask_n: 2
        time_mask_t: 100
        time_mask_p: 1.0
    cmvn:
        norm_means: True
        norm_vars: True

testing:
    beam_size: 10
    alpha: 1.0
    postproccess: True
    bpe_type: "sentencepiece"
    sacrebleu:
        remove_whitespace: True
        tokenize: "13a"

training:
    #load_model: "/scratch/ohta/models/mustc_asr_seed123/best.ckpt"
    reset_best_ckpt: False
    reset_scheduler: False
    reset_optimizer: False
    reset_iter_state: False
    random_seed: 789
    optimizer: "adam"
    adam_betas: [0.9, 0.99]
    scheduling: "warmupinversesquareroot"
    learning_rate: 2.0e-3
    learning_rate_min: 1.0e-6
    learning_rate_warmup: 10000
    clip_grad_norm: 10.0
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_multiplier: 8
    normalization: "batch"
    batch_size: 80000
    batch_type: "token"
    eval_batch_size: 80000
    eval_batch_type: "token"
    early_stopping_metric: "eval_metric"
    epochs: 100
    updates: 100000
    validation_freq: 1000
    logging_freq: 100
    eval_metrics: "wer"
    model_dir: "/scratch12t/ohta/models/mustc_v2_asr_seed789"
    overwrite: True
    shuffle: True
    use_cuda: True
    fp16: False
    max_output_length: 100
    print_valid_sents: [0, 1, 2]
    keep_ckpts: "best"
    num_ckpts: -1
    loss: "crossentropy-ctc"
    ctc_weight: 0.3
    num_workers: 8

model:
    initializer: "xavier"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 12
        num_heads: 8
        embeddings:
            embedding_dim: 80
            #embedding_dim: 512
            #scale: True
            #dropout: 0.
            #freeze: False
        # typically ff_size = 8 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.15
        freeze: False
        subsample: True
        conv_kernel_sizes: 5,5
        conv_channels: 512
        in_channels: 80
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
            freeze: False
        # ff_size = 8 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.15
        freeze: False
